export { CapacityTabContent } from './ui/CapacityTabContent'
export { DestinationsTabContent } from './ui/DestinationsTabContent'
export { InventoryCategoriesTabContent } from './ui/InventoryCategoriesTabContent'
export { TermsAndConditionsTabContent } from './ui/TermsAndConditionsTabContent'
export { default as SpecialPricesBody } from './ui/SpecialPricesBody'
